### ISSUE TITLE
Support for Canon 60D cameras

### ISSUE THREAD

**Issue by neilschelly** [musselwhizzle/Focus-Points#91] opened 2017-01-13 00:38 UTC
I've started some work on Canon support, but it probably should be a lot cleaner than what's currently in place. I found that all the information for the which focus points are selected, which are in focus, and the exact coordinates are all in the EXIF on my Canon 60D. Since that's not exactly the most modern Canon at this point, I would venture the same or better information can be found in newer ones.

I documented what the EXIF data looks like and created a map file for the Canon 60D coordinates in a branch, if someone is interested in using it to add broader Canon support based on this. It should be easy to generate maps of any Canon camera that has similar AF data to mine automatically.

See my branch at https://github.com/neilschelly/Focus-Points/tree/canon-60d
I'd be happy to answer any questions or supply any sample images if it would be helpful to someone motivated to continue this work.

**Comment by musselwhizzle** [comment] 2017-01-13 00:47
Hi, Thanks a bunch for this. I may have some good/bad news for you. I think you're camera is already supported. Can you please download the latest from the master repo and try it?

**Comment by neilschelly** [comment] 2017-01-13 01:02
I just bumped to your latest master, removed and reinstalled the plugin, and I don't see any focus points come up when I click "Show Focus Point" in the plugin extras menu. I just see the image itself in the window. If I do Show Metadata, it comes up as a blank/empty window.

I can try to troubleshoot a bit more later, or I can send you the images I'm looking at if that would help you. I don't have a lot of time to contribute unfortunately. I had the best of intentions when I forked this, but it's going to be awhile before I can really contribute too much more coding time.

**Comment by musselwhizzle** [comment] 2017-01-13 01:04
great. I'll add your mapping file then. thanks for checking that. 1 final thing if you dont mind. can you PR some sample images into here for me
https://github.com/musselwhizzle/Focus-Points-Sample-Images

**Comment by neilschelly** [comment] 2017-01-13 01:34
Done.

**Comment by musselwhizzle** [comment] 2017-01-13 02:53
Using supplied sample images, current canon 60D is off. Adjust or used supplied point map (See Screenshot)

<img width="988" alt="screen shot 2017-01-12 at 6 52 19 pm" src="https://cloud.githubusercontent.com/assets/2308674/21916899/5fdd2322-d8f8-11e6-958a-98235b16ef2f.png">

**Comment by philmoz** [comment] 2017-01-13 04:27
I can't reproduce this - all the 60D sample images show correct focus points with the latest master branch on my system.
e.g.
![screen shot 2017-01-13 at 3 24 23 pm copy](https://cloud.githubusercontent.com/assets/9474356/21918371/b5ee0860-d9a4-11e6-81b4-d9c3c0121c88.jpg)

**Comment by musselwhizzle** [comment] 2017-01-13 05:06
weird, I dont get that at all. None of the 60D images work for me. Both the 40D and 80D work great.

**Comment by musselwhizzle** [comment] 2017-01-13 05:08
@rderimay - could you try and see what you get?

**Comment by musselwhizzle** [comment] 2017-01-13 05:41
PS: attached is my metadata file. Is this the same as you're getting? 
[IMG_8568-metadata.txt](https://github.com/musselwhizzle/Focus-Points/files/703583/IMG_8568-metadata.txt)

**Comment by philmoz** [comment] 2017-01-13 05:47
Your metadata matches what I see. What does a full log look like?

**Comment by musselwhizzle** [comment] 2017-01-13 05:49
log attached: 

[libraryLogger.txt](https://github.com/musselwhizzle/Focus-Points/files/703590/libraryLogger.txt)

**Comment by musselwhizzle** [comment] 2017-01-13 05:56
It's related to the dialog size which is a result of your screen size. Change the dialog to something small here: 
```
local contentWidth = appWidth * .9
  local contentHeight = appHeight * .9
```

and it will completely break (or fix it in my case)

<img width="1235" alt="screen shot 2017-01-12 at 9 55 31 pm" src="https://cloud.githubusercontent.com/assets/2308674/21919793/ff48dfd2-d911-11e6-9604-45a2a8eff130.png">

**Comment by musselwhizzle** [comment] 2017-01-13 06:07
it has to do with the piecing together of the focus box. If there's not enough space to draw all 4 corners, the script completely fails. 

<img width="172" alt="screen shot 2017-01-12 at 10 05 46 pm" src="https://cloud.githubusercontent.com/assets/2308674/21920026/63b6a688-d913-11e6-9cb8-d96d0af62daf.png">
<img width="215" alt="screen shot 2017-01-12 at 10 05 25 pm" src="https://cloud.githubusercontent.com/assets/2308674/21920025/63b69562-d913-11e6-964f-fd0584f7de94.png">

Look how close the first image is. When I make the dialog box just a hair smaller, the focus box goes away. We fix this issue, and it should be resolved @rderimay

**Comment by philmoz** [comment] 2017-01-13 06:18
Yes, this line causes the small boxes to be ignored:
     if dist > 25 then

**Comment by musselwhizzle** [comment] 2017-01-13 06:27
I agree. It looks like a bug when they dont show up. The first image I posted isn't useable. I'll let @rderimay chime in before we change the code.

**Comment by musselwhizzle** [comment] 2017-01-13 06:31
@neilschelly let's see if we can get yours working. First off are you mac or PC. 
> If I do Show Metadata, it comes up as a blank/empty window
That's not a good sign. It wont work with that blank. 

Set your logging to debug (as shown in the screenshot), and then attach your log file here please. 
<img width="684" alt="screen shot 2017-01-12 at 10 29 34 pm" src="https://cloud.githubusercontent.com/assets/2308674/21920547/b4f53714-d916-11e6-8d02-d8c318da5a6b.png">

Your log file is located under ~/Documents/libraryLogger.log. Rename it to libraryLogger.txt so this webpage will let you upload it.

**Comment by rderimay** [comment] 2017-01-13 07:01
Good Morning :-)
This is intended behavior. I will PR an improvement by displaying them in all cases but limiting their proximity so that it still looks like an af point.

**Comment by rderimay** [comment] 2017-01-13 09:21
Fixed in PR #98

**Comment by musselwhizzle** [comment] 2017-01-13 18:38
Yes, the current master resolves my issue. Still need to figure out why @neilschelly metadata is completely blank, then we'll be all set!

**Comment by rderimay** [comment] 2017-01-13 19:20
When do you write blank metadata, is it something that is not working on my code or in the metadata dialog code ?
Don't understand if I need to test something or not actually.


On 13 janvier 2017 at 19:39:06, Joshua Musselwhite (notifications@github.com) wrote:

Yes, the current master resolves my issue. Still need to figure out why @neilschelly metadata is completely blank, then we'll be all set!

**Comment by musselwhizzle** [comment] 2017-01-13 19:21
I need a response from Neil. You're off the hook for now :)

**Comment by rderimay** [comment] 2017-01-13 19:22
Ok !


On 13 janvier 2017 at 20:21:40, Joshua Musselwhite (notifications@github.com) wrote:

I need a response from Neil. You're off the hook for now :)

**Comment by neilschelly** [comment] 2017-01-13 19:32
Sorry folks, my day job has nothing to do with this. The Mac I use for photography is at home. I hope to be able to get the test data you need later tonight.

**Comment by neilschelly** [comment] 2017-01-14 00:29
I just upgraded the plugin to the latest/greatest. Focus points show up and the metadata page is no longer empty. I'm all good now! Thanks a ton for the effort.

**Closed** 2017-01-14 00:30 UTC
