### ISSUE TITLE
Plugin not showing entries on Plugin Extras

### ISSUE THREAD

**Issue by mbertuol** [musselwhizzle/Focus-Points#169] opened 2023-11-12 14:47 UTC
I have installed the plugin and it does not show any entries on Plugin Extras. What am doing wrong?

Here are some screenshots.

<img width="518" alt="2" src="https://github.com/musselwhizzle/Focus-Points/assets/5726026/9a0e138d-e702-484b-a6ce-3ea0b3ac19bd">
<img width="670" alt="Screenshot 2023-11-12 090830" src="https://github.com/musselwhizzle/Focus-Points/assets/5726026/c2c68461-12c5-44bb-a99d-4f038202b99e">
<img width="426" alt="Screenshot 2023-11-12 091146" src="https://github.com/musselwhizzle/Focus-Points/assets/5726026/f2813829-aa09-42a8-baa9-05b17185885f">

**Comment by capricorn8** [comment] 2023-11-12 18:35
You're not doing anything wrong. The plugin is designed to appear under the Library -> Plugin Extras menu.

However, it can be easily changed to also work also from the File menu. Just unpack the attached file and replace the info.lua file that came with the plug-in installation with this one.

[infolua.zip](https://github.com/musselwhizzle/Focus-Points/files/13328803/infolua.zip)

**Comment by mbertuol** [comment] 2023-11-12 21:02
Thank you so much for your reply. I should have read the instructions more carefully. In the sample below I am showing a screenshot of my screen (resolution below). The viewer cannot have its size adjusted and, therefore, the full image cannot be displayed in it is entirety. The photo was taken with a Sony A7R V (I can confirm it works with this camera and it can be added to the supported cameras list) and its resolution is also shown below. Do you have any recommendation on how to fix this issue? Ideally the viewer windows should not be bigger than the screen it is being displayed.

![3](https://github.com/musselwhizzle/Focus-Points/assets/5726026/b2b84ae8-f124-4edc-b1ca-c970e46c7866)
<img width="759" alt="Screenshot 2023-11-12 155544" src="https://github.com/musselwhizzle/Focus-Points/assets/5726026/ad121275-f776-46e0-96f6-575765ebded2">
<img width="170" alt="Screenshot 2023-11-12 155942" src="https://github.com/musselwhizzle/Focus-Points/assets/5726026/deab7bd4-ba14-4b4e-bf23-f276466771f1">

**Comment by capricorn8** [comment] 2023-11-13 07:40
Could you provide the image file so I can look into this?

**Comment by ropma** [comment] 2023-11-13 13:52
Can also activate debug logging. Reproduce the problem and provide the log file (<users>\Documents\LrClassicLogs\libraryLogger.log.). Don't to the switch logging off again.  

What display resolation has your screen?

Roland

PS: I have no problems with Sony A7R V files.

**Comment by mbertuol** [comment] 2023-11-13 15:30
I appreciate your time for looking into this. I made a recording showing my entire screen (resolution 3840x2160). When Lightroom is using about a third of the screen, the plugin viewer shows its window properly. However when Lightroom is maximized, the plugin viewer window goes off boundaries. I have installed it on my laptop and I have experienced the same behavior. The laptop screen resolution is 2880x1800.

I am also sending you a sample image. Since both files are big, I created a zip and made it available to you: https://www.dropbox.com/t/uKcEfws75V9NsFNT

I turned on debugger but could not find any *.txt with debug info or any *.log file. Where should I find the debug file?

**Comment by ropma** [comment] 2023-11-13 15:53
I assume you are running Window.

The name of log file is 'libraryLogger.log'. It is the the folder '_your_user_name_\Documents\LrClassicLogs', e,g, C:\Users\roland\Documents\LrClassicLogs

**Comment by mbertuol** [comment] 2023-11-13 16:06
Here you have the debug file:

[libraryLogger.log](https://github.com/musselwhizzle/Focus-Points/files/13336763/libraryLogger.log)

**Comment by capricorn8** [comment] 2023-11-13 16:43
I'm unable to reproduce this behavior on my Windows machine with QHD monitor (2560x1440).

**Comment by ropma** [comment] 2023-11-13 17:32
In the log file I can see, that you made several attempts. The size of created Focus Points windows were 2215x1477 and 1591x1060 pixels respectively. Both should fit on your screen without any problems.
Are you using a scale and a different screen resolution (other than the actual resolution of the screen?)

**Comment by mbertuol** [comment] 2023-11-13 17:39
I do need to use 150% scaling because the monitor has a 3840 x 2160 native resolution. If I leave the scale at 100%, everything is so tiny on the screen that is very difficult to work.
I guess the plugin is not taking into consideration the scale. 

<img width="803" alt="image" src="https://github.com/musselwhizzle/Focus-Points/assets/5726026/ce80fe5a-3ead-409d-8e2a-4f5dbf5a9634">

**Comment by mbertuol** [comment] 2023-11-13 17:40
I believe that if you set your scale to 125% or 150% you should be able to reproduce the issue.

**Comment by ropma** [comment] 2023-11-13 17:43
I'll check it tomorrow..

**Comment by mbertuol** [comment] 2023-11-13 17:47
If I use 100% scale, it show correctly.

![2](https://github.com/musselwhizzle/Focus-Points/assets/5726026/8e3d4ca2-c032-42cb-a66d-14ce5b97fcd1)

**Comment by capricorn8** [comment] 2023-11-13 20:36
> I believe that if you set your scale to 125% or 150% you should be able to reproduce the issue.

By default, I use 114%. I now tried with 100%, 150% and 200% but in all cases the focus pointer viewer window shows correctly.

**Comment by mbertuol** [comment] 2023-11-13 21:46
Not sure what to do then. In my case it only works at 100% scale…

**Comment by capricorn8** [comment] 2023-11-14 08:23
It might be an issue specifically with LrC 13:
[https://www.lightroomqueen.com/community/threads/lr-mogrify-add-borders-etc-not-working-with-lrc-13.48607/](url)

There seem to be a number of plugins affected by this, all of them use Mogrify - as the focus point viewer does.

AFAIR @ropma has implemented this part of the plugin, let's see what with he comes up from analyzing your logfile.

**Comment by ropma** [comment] 2023-11-14 14:25
Today I've tested the plugin with 125% - and no problem. I'm using the latest Lightroom version 13.0.1

Which version a you using?

PS: I don't it the issue of the lightroomqueen forum. Mogrify seen to work. The screen size is wrong.

**Comment by mbertuol** [comment] 2023-11-14 14:59
I am using version 13.0.1 as well. I have the same issue both with my laptop (that has a lower screen resolution) and with my desktop. 

I have tested with 4 scale options that my desktop provides me:
<img width="784" alt="image" src="https://github.com/musselwhizzle/Focus-Points/assets/5726026/785f1fb5-0b14-40f9-a641-0e36a36c0993">

Here are the results:
100%
![100](https://github.com/musselwhizzle/Focus-Points/assets/5726026/8f5e3662-47af-4aaa-aaf3-ffb4bc0a00fe)


125%
![125](https://github.com/musselwhizzle/Focus-Points/assets/5726026/4bb30ba7-2b49-458e-bd31-cf7167e27f2e)

150% (my default)
![150](https://github.com/musselwhizzle/Focus-Points/assets/5726026/6eee393c-b1e7-43ab-9c31-89564649f8fb)

175%
![175](https://github.com/musselwhizzle/Focus-Points/assets/5726026/ff6a1eee-e5e8-4d36-a00e-6c07c2b8c85e)

200%
![200](https://github.com/musselwhizzle/Focus-Points/assets/5726026/9e8d34a3-54b9-4cc1-a78f-116880b5f7f8)

**Comment by mbertuol** [comment] 2023-11-14 15:23
Based on the screenshots above, could you please test at 150%

**Comment by ropma** [comment] 2023-11-14 15:29
You are right!! At 150% I have the some problem. I need to investigate a little more..

**Comment by ropma** [comment] 2023-11-14 18:35
This is bug in the Lightroom API. For more details see bug report in the [Adobe community]( https://community.adobe.com/t5/lightroom-classic-bugs/p-sdk-lrsysteminfo-displayinfo-and-appwindowsize-return-wrong-units-of-pixels-on-windows/idi-p/12719960?profile.language=en)

The Focus Point plugin use LrSystemInfo..appWindowSize(). 
I don't see a easy workaround.

**Comment by mbertuol** [comment] 2023-11-14 19:03
Ropma, just wondering here... Would it be possible that you could show the focus point(s) as an overlay in every single photo? 
If we could see as an overlay, there would be no need to open the viewer and would be much easier to choose photos for focus stacking. 
It would be similar to what you would see in the Sony camera LCD.
Imagine something like this:

<img width="1006" alt="image" src="https://github.com/musselwhizzle/Focus-Points/assets/5726026/2985e8a6-a029-4c48-af40-694925576804">

**Comment by capricorn8** [comment] 2023-11-14 19:12
> This is bug in the Lightroom API. For more details see bug report in the [Adobe community](https://community.adobe.com/t5/lightroom-classic-bugs/p-sdk-lrsysteminfo-displayinfo-and-appwindowsize-return-wrong-units-of-pixels-on-windows/idi-p/12719960?profile.language=en)
> 
> The Focus Point plugin use LrSystemInfo..appWindowSize(). I don't see a easy workaround.

Plus, the error has already been reported in early 2022. So, there is little hope that this will be fixed at all.

@mbertuol What is the closest scale factor to 150% where this issue doesn't happen?

I'm asking because in the past I had a similar issue with display scaling in PS, resulting in invisible dialogs - see [here](https://community.adobe.com/t5/photoshop-ecosystem-discussions/ctrl-f-in-app-search-dialog-is-invisible-but-works-with-keyboard/m-p/10681551#M271196). Maybe it's sufficient to choose eg. 146%? Have you tried this already?

**Comment by mbertuol** [comment] 2023-11-14 19:19
@capricorn8  I am not able to enter any given number in Windows 11 scale option. I can only choose from the dropdown menu. Therefore, it goes from 125% to 150%.

On a different subject, do see any feasibility of having a focus point overlay like the simulation I posted above?

**Comment by mbertuol** [comment] 2023-11-14 19:50
@capricorn8 Thank you for that. I never realized it could be changed that way. I tried 140% and 145% and both did not work.

The only thing that works is changing the font size in Lightroom. Preferences, Interface, Font size. You should choose Medium. Then it displays correctly even though Windows is to 150% scale. The downside is the interface (not the menus though) become too small...

**Comment by ropma** [comment] 2023-11-14 20:06
> Ropma, just wondering here... Would it be possible that you could show the focus point(s) as an overlay in every single photo?

Using overlays is the idea of the Mac version. But it does work on Windows: see https://github.com/musselwhizzle/Focus-Points/issues/70 
The current Windows implementation is a workaround for this issue.

**Comment by capricorn8** [comment] 2023-11-15 08:36
@ropma My interpretation of mbertuol's question whether it would be possible to add a focus point overlay to the original image display in LR, similar to the Loupe Overlay. AFAIR the plugin always had a separate window.

**Comment by ropma** [comment] 2023-11-15 12:37
The Lightroom API does not allow to draw or create overlays to the original image display. Thus also the Mac version create a second image window.

Due to a bug in the Windows Lightroom API, it is not possible to determine the available image size and thus calculate the correct window size. But as a workaround you could specify the scaling in the Options dialog and thus calculate the correct window size.
What you think?

**Comment by mbertuol** [comment] 2023-11-15 12:44
Thank you for the explanation.
I could do that if you tell me the steps.
As an alternative option, would there be a way to set a fixed window size? Maybe in the info.lua file…

**Comment by ropma** [comment] 2023-11-15 13:28
A fixed window size is not flexible, this I not prefer an option for it, e.g.

![Screenshot 2023-11-15 142149](https://github.com/musselwhizzle/Focus-Points/assets/37225368/b7c478ac-0c06-4f60-891a-40fa888ff3b7)

**Comment by ropma** [comment] 2023-11-15 14:54
I've have created a new local branch in my local repository:
https://github.com/ropma/Focus-Points/tree/win_scaling

The branch offers the scaling option. Could you please test it?

**Comment by mbertuol** [comment] 2023-11-16 22:12
> I've have created a new local branch in my local repository: https://github.com/ropma/Focus-Points/tree/win_scaling
> 
> The branch offers the scaling option. Could you please test it?

It worked! I really appreciate your efforts! Thank you so much!

**Comment by musselwhizzle** [comment] 2023-11-16 22:27
Anything y'all want to merge in?

**Closed** 2024-07-05 15:43 UTC
